### PR TITLE
feat(ebay-carousel): changed carousel stories to support storybook knobs

### PR DESCRIPTION
**Pull request by agliga**
## Description
Added knobs to storybook for carousel
Removed a lot of the stories and have them all controlled by knobs

## Screenshots

Screen Shot 2021-04-27 at 1 23 05 PM

### CODE REVIEW

**Comment by ianmcburnie** [comment]
This is REALLY nice! I love the accessibility panel too:

Screen Shot 2021-04-27 at 1 42 16 PM

One question, is the image treatment supposed to look like this:

Screen Shot 2021-04-27 at 1 41 41 PM

**Review by austingardner — CHANGES_REQUESTED** [review]
Overall looks really good! The image treatment is a bit broken though, let's fix that really quick

**Review by ianmcburnie — APPROVED** [review]
Nice work! Looking forward to seeing all our stories cleaned up like this :-)

**Review by austingardner — APPROVED** [review]
LGTM!

**Pull request merged**
