### PR TITLE
Renaming <ebay-listbox> to <ebay-select>

### PR DESCRIPTION
**Pull request by seangates**
## Description
To better align with the described purpose for this component, it has been renamed from `<ebay-listbox>` to `<ebay-select>`. This will aid developers in understanding it as a form control, and it will also aid us in speaking about the differences between it and the `<ebay-menu>`.

Lastly, this change more closely matches the way we describe how HTML currently works.

## References
Is part of the work for #4.

### CODE REVIEW

**Comment by seangates** [comment]
@ianmcburnie Yes, you might have to manually delete some things. I know that Git leaves folders behind, etc.

**Comment by ianmcburnie** [comment]
@sgates Ok. Our `clean` script needs updating to take care of this (not in this PR)

**Comment by sgates** [comment]
@ianmcburnie sweet.

**Comment by seangates** [comment]
@sgates Sorry about this again. I will try and get a handle on @ianmcburnie. 🤣

**Comment by ianmcburnie** [comment]
Oh dear, I feel like I need to put a dollar in a pot every time I make one of these Sean Gates violations.

**Comment by sgates** [comment]
Thats the problem with having such a cool name I guess @seangates @ianmcburnie 🤣

**Pull request merged**
