### PR TITLE
rebase with master to pick up Dylan's travis changes

### PR DESCRIPTION
**Pull request by sendlo**
## Description
Rebase with master

## Context
So this can be tested along with the 0.9.0 pre release before its final.

### CODE REVIEW

**Comment by yomed** [comment]
Maybe simpler to leave this one in master and pick it up later. It's has no external impact.

**Comment by sendlo** [comment]
I thought about it, but that means it doesn't get any testing before its released.  I agree it shouldn't effect anything external, but I'm playing it safe this way.

**Comment by yomed** [comment]
It won't get testing anyway. There's nothing to test beyond what Dylan already did in creating the PR from his fork.

**Comment by sendlo** [comment]
Yeah, I understand.  I didn't mean that it needs to be tested, but I don't think its good practice to publish a module that hasn't been signed off by QE as a whole unified build.  Even if he won't see any difference with or without Dylan's change.

**Pull request merged**
