### PR TITLE
feat(segmented-buttons): new component

### PR DESCRIPTION
**Pull request by agliga**
## Description

Component part for segmented button

## References
https://github.com/eBay/ebayui-core/issues/1898

## Screenshots
Screen Shot 2023-05-10 at 1 53 54 PM

### CODE REVIEW

**Review by LuLaValva — COMMENTED** [review]
Looks awesome, the only problem I could find is that the storybook file and the directory disagree about the name of the component. Is it `segmented-button` or `segmented-buttons`?

**Review by saiponnada — CHANGES_REQUESTED** [review]
Looks good to me.  Only suggestion that might need to be considered(not mandatory) is making sure these buttons are 44 x 44 dp touch target size so that users might not bump into one another.

As Luke mentioned, minor tweaks. Looks like the name need to be changed in few places 
 - Folder need to be renamed to ebay-seg**~~e~~**mented-button**s**
 - Server test describe needs to be updated as well - L11
 - Story book docs need be updated at L95

**Comment by agliga** [comment]
> Looks good to me. Only suggestion that might need to be considered(not mandatory) is making sure these buttons are 44 x 44 dp touch target size so that users might not bump into one another.
> 
> As Luke mentioned, minor tweaks. Looks like the name need to be changed in few places
> 
> * Folder need to be renamed to ebay-seg**~e~**mented-button**s**
> * Server test describe needs to be updated as well - L11
> * Story book docs need be updated at L95

Okay, should be ready for rereview. 
The 44x44 part should be a skin change. I think we can revisit later. 
But renamed all tests and code.

**Review by LuLaValva — APPROVED** [review]
Thanks Andrew! Looks great

**Comment by saiponnada** [comment]
yeah, looks like new rule mandates 24 x 24 dp and is not effective yet. so we can just keep it in backlog and make sure it corresponds to that before the rule becomes effective.

**Review by saiponnada — APPROVED** [review]
Looks good to me.

**Pull request merged**
