### PR TITLE
Icon import 12.3.0

### PR DESCRIPTION
**Pull request by LuLaValva**
## Description

- import icons from ebay/skin#2083

### CODE REVIEW

**Review by ArtBlue — CHANGES_REQUESTED** [review]
Some icons look to not have been imported accurately. 
image

**Comment by ArtBlue** [comment]
The changes appear to be good. It should be good to go once we fix the build errors.

**Comment by LuLaValva** [comment]
Thanks @ArtBlue, I updated the tests and it looks like the build is successful now

**Review by ArtBlue — APPROVED** [review]
@LuLaValva , yep. Looks good now!

**Pull request merged**
