### PR TITLE
convert to string to compare the option array & selected option

### PR DESCRIPTION
**Pull request by PrashantAshok**
## Description
The 3rd example on marketplace doesn't work

## Context
Select UI doesn't change on click and on keyboard when the options are rendered dynamically.

### CODE REVIEW

**Comment by ianmcburnie** [comment]
@PrashantAshok CI Job failed at following unit test:

```
1 failing
  1) src/components/ebay-select
       given the listbox is in the default state
         when the down arrow key is pressed
           then it emits the listbox-change event with the correct data:
      AssertionError: expected '1' to equal '2'
      + expected - actual
```

**Comment by seangates** [comment]
Yup, we're looking at it together, @ianmcburnie. Will have an update soon.

**Comment by ianmcburnie** [comment]
What's the latest on this? Is fix going into 0.2.0?

**Comment by seangates** [comment]
The latest is that I haven't been able to get past the failed test, and it only happens with this branch, so it's clearly something with how this logical change affects the test. Let me work with @PrashantAshok to close the loop today.

**Pull request merged**
