### PR TITLE
Update Marko CLI

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
I released a new version of Marko cli so we can stop relying on the canary release.

### CODE REVIEW

**Comment by ianmcburnie** [comment]
@seangates any reason to keep this back till 0.8.0 given that it's dev env related?

**Comment by ianmcburnie** [comment]
Actually, it does seem to update babel runtime in yarn.lock, if that's something that has an impact on our actual components then maybe we do leave it for now. @DylanPiercey?

**Comment by DylanPiercey** [comment]
@ianmcburnie the yarn.lock can never break the published components, only our builds / dev environments. Also in this case the the `@babel/runtime` is additive. There still exists the old `babel-runtime` in our lock.

**Comment by DylanPiercey** [comment]
I mean to say it can't cause a regression to anything except our dev environment (and the build is passing). The lock file only locks down the files for us during dev. When people install our modules they get the latest tree which has nothing to do with our lock file.

**Comment by ianmcburnie** [comment]
Oh, duh, it's under 'devDependencies' - silly me!

**Pull request merged**
