### PR TITLE
added focus and blur events to switch component

### PR DESCRIPTION
**Pull request by shanimal**
## Description
Added focus and blur to switch component

## Context
n/a

## References
n/a

## Screenshots
n/a

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Thanks for the PR @shanimal . Out of curiosity, are these blur and focus hooks something that your app actually needs? Or just something you think that might be needed?

**Comment by shanimal** [comment]
Hi Ian, thanks for the quick response. Good question. Yes, we need this for user and funnel metrics within our product input form. From these we determine pain points for users and better understand where to focus (no pun intended) our energy.

**Comment by shanimal** [comment]
@ianmcburnie After reviewing this for myself, you are right, we probably don't need this after-all. 

I can reopen if I need support for it.

Sorry.

**Comment by ianmcburnie** [comment]
No problem!

**Pull request closed without merging**
