### PR TITLE
Fixing combobox for mWeb;

### LINKED ISSUE #389: combobox: IOS- mweb - combobox doesnt expand the second time
# Bug Report

## Description
In Iphone x -  chrome and safari
go to http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStaging2/ds4
scroll to the combobox section
expand any of the combobox 
collapse it
try expanding the same again

### PR DESCRIPTION
**Pull request by seangates**
## Description
- changes input type to button
- removes the `role="combobox"`

## Context
Combobox was having many issues when used in mWeb. This is a short term fix in order to support teams who have already implemented combobox as-is.

## References
Fixes #389, #287, #229

### CODE REVIEW

**Comment by yomed** [comment]
LGTM. Will take another look after the Skin changes are in.

**Comment by seangates** [comment]
@yomed Skin changes are in, and published in v6.0.0-4.

**Comment by seangates** [comment]
@yomed Shoot. I could have sworn I did that. I'll fix and send another PR.

**Comment by seangates** [comment]
@yomed Updated. Check once more?

**Comment by yomed** [comment]
Did you want to leave the checkmark placement alone for now?

**Comment by seangates** [comment]
@yomed Working on it. It's part of Skin.

**Comment by seangates** [comment]
@yomed https://github.com/eBay/skin/pull/362

**Pull request merged**
