### PR TITLE
Combobox: Allow cursor to be handled natively

### LINKED ISSUE #641: Combobox: unable to edit text in the middle or pre-pend text to an existing text
# Bug Report

## Description
Repor;
Click on a combobox
type some text
Try adding/deleting some text in the middle of the currently added text
The cursor automatically shifts to the right
https://www.loom.com/share/3b19029c733c4683bc91efa4ad0b3cb9

## Workaround
The user has to delete the entire text and start again

### LINKED ISSUE #701: Combobox: First attempt to selecting an option from the list gets the cursor to go the start.
# Bug Report

## Description
when I open up the editable combo box first time and select an option then the cursor is moved to the start instead of the end.

### PR DESCRIPTION
**Pull request by seangates**
## Description
- adds long text example (wider than the textbox)
- removes the moveCursorToEnd and related references
- created a `keyup` handler and move the text input handler to the `keyup` handling
- set the DOM's input value before state change and re-render

## References
Fixes #641 
Fixes #701

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Set `axis` to `y` in makeup-active-descendent to fix issue found by Andrew:

https://github.com/makeup-js/makeup-active-descendant/blob/master/src/index.js#L10

**Comment by seangates** [comment]
Tried `axis: 'y'`, but it doesn't appear to be working correctly. Checking with makeup-active-descendent now.

**Comment by seangates** [comment]
Ah, I didn't have the newest version ...

**Comment by seangates** [comment]
@ianmcburnie Updated to only allow the up and down arrows.

**Comment by ianmcburnie** [comment]
For the issue @agliga mentioned I added a `reset` method to `makeup-active-descendant` in a recent patch. This might help with removing the highlighted item. It should be tackled in a separate PR though.

**Comment by seangates** [comment]
@agliga @ianmcburnie Yeah, this is related to #633.

**Pull request merged**
