### PR TITLE
Updated storybook, added code viewer, and directory support

### PR DESCRIPTION
**Pull request by agliga**
## Description
* Updated storybook to the latest version, added support for it to work
* Added code syntax viewer
* Made center examples
* Added support for groups items
* Put button into it's own group (did this to test the new group items)
* Misc cleanup for storybook code
* Reran `storytbook:build` to make sure things are working
* Also upgraded all devDeps (part of upgrading storybook)

## Context
For code syntax, I had to basically compile all raw code using webpack. Then it gets loaded and read when each code is loaded. 
I had to do the lookup with the "ID" instead of filename since the ID was available in each module while filename was not.
I used the old highlights plugin for now, but we can switch

__Note__ I saw a couple of bugs, carousel does not seem to work and breadcrumbs are not showing up. I will address those in a future PR since this one is getting too large.

## References
#1018
#1234 (infastructure work for this)
#1029 

## Screenshots
Screen Shot 2021-01-20 at 10 16 57 AM
Screen Shot 2021-01-20 at 10 17 05 AM
Screen Shot 2021-01-20 at 10 17 13 AM
Screen Shot 2021-01-20 at 10 17 46 AM

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Very cool set of changes. Love the code syntax viewer.

Couple of nitpicks:

1. Switch: each story currently shows two instances of the switch. On and off. Please separate those states out into separate stories (this is better for visual regressing testing)
2. Badge: I think we can move the menu and icon stories to their respective components (menu/menu-button and button)
3. Filter: same as above. Some stories are showing more than one instance. If you see this anywhere else, please also fix so that we always have one instance of component per story.

**Comment by agliga** [comment]
> Very cool set of changes. Love the code syntax viewer.
> 
> 
> 
> Couple of nitpicks:
> 
> 
> 
> 1. Switch: each story currently shows two instances of the switch. On and off. Please separate those states out into separate stories (this is better for visual regressing testing)
> 
> 2. Badge: I think we can move the menu and icon stories to their respective components (menu/menu-button and button)
> 
> 3. Filter: same as above. Some stories are showing more than one instance. If you see this anywhere else, please also fix so that we always have one instance of component per story.

Sounds good. I will plan to do them in a follow up pr. I have a couple of fixes to get in but wanted to separate them out so this pr doesn't get too big

**Comment by ianmcburnie** [comment]
No problem. It would probably good if you walk us through some of the plumbing/configuration/plugin aspects.

**Review by ianmcburnie — APPROVED** [review]
Happy for this to go in now, if it helps you juggling branches.

**Pull request merged**
