### PR TITLE
Carousel: Native scrolling with css snap points.

### LINKED ISSUE #463: Carousel:continuous -  chrome - Native scrolling animation slow in android
# Bug Report

## Description
pls refer to the issue for IOS here.
https://github.com/eBay/ebayui-core/issues/454

its the same in android

https://www.useloom.com/share/ae118b3f471a4ace9a428843c6c6571e

### LINKED ISSUE #465: Carousel: adjust speed and reach of the carousel "flick" movement
# Bug Report

## Description
In IOS Safari, after the auto adjust feature added in 1.1.0, it is no longer easy to get to the end of the carousel (>10 cards) in one flick.
The flick speed and the speed with which the carousel moves does not match.

### LINKED ISSUE #466: Carousel: continuous -the white space that appears and disappears when we try to scroll past the last card is no longer present
# Bug Report

## Description
the white space that appears and disappears when we try to scroll past the last card is no longer present.
With the current design it looks more like the carousel is stuck in the position when I try to scroll past the last card.

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
This PR switches the carousel to prefer using native scrolling with [css snap points](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap_Points) where available.
If the browser does not support one of the variants of css snap points then it falls back to using transforms without native scrolling.

This also has support for native scrolling (with snap points) using trackpads on desktop.

## Context
The reason I decided to make the fallback just the simple transform based implementation is:
a) It seems that most mobile browsers support the css snap points (or some version of it) 🎉.
b) This allows for the exist events to stay as is and work in all cases they used to work.
c) Should ensure a working experience for basically all devices.

## References
implements #476 
fixes #466 
fixes #465 
fixes #463 

## Notes
Because it is impossible to speed up these native scroll animations the tests now take a chunk longer to run.

## Screenshots
native-scrolling-carousel

### CODE REVIEW

**Comment by senthilp** [comment]
@DylanPiercey Haven't reviewed it fully. But thanks for this :+1:

**Comment by ianmcburnie** [comment]
@DylanPiercey Your link in the description above goes to a deprecated version of CSS scroll snap. Are you using a mix of the old and new spec?

**Comment by DylanPiercey** [comment]
@ianmcburnie it’s using the new spec will fallbacks to the old.

**Comment by ianmcburnie** [comment]
@DylanPiercey Only issue I am seeing is in Firefox on OSX, with the vertical scroll bar showing up:

screen shot 2018-11-14 at 10 48 59 am

**Comment by DylanPiercey** [comment]
@ianmcburnie that's strange. I'm not seeing that on my version of Firefox. Are you able to see what property is causing that?

**Comment by ianmcburnie** [comment]
Possibly the height/line-height of the li items, but not completely sure. Occurs in 62.0.3 and 63.0.1.

**Pull request merged**
