### PR TITLE
Combobox: Fix value change test;

### LINKED ISSUE #988: Combobox: change event is not fired when a new value is entered
# Bug Report

## Description

The current behavior to check for whether the combobox value changed is for the `newValue` (e.g. what is currently in the `value` property of the text input) is tested against ... `this.inputEl.value` ... which is the same thing. Hence, we're simply checking if the value equals itself.

https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-combobox/index.js#L129

## Workaround

None.

### PR DESCRIPTION
**Pull request by seangates**
## Description
- change test for text input and whether the change event should fire on blur

## Context
Presently the test tests whether the entered value equals ... the entered value.

## References
Fixes #988

### CODE REVIEW

**Comment by DylanPiercey** [comment]
I don’t think this issue exists in the v5 branch. Would you be able to put up a PR to that branch which brings these test changes over to verify?

**Comment by seangates** [comment]
@DylanPiercey Sure. I can do the test over there, too.

**Comment by ianmcburnie** [comment]
Let's track anything required in port in #956 Feel free to re-open that ticket.

**Comment by seangates** [comment]
All: https://github.com/eBay/ebayui-core/pull/990

**Pull request merged**
