### PR TITLE
fix(calendar): timezone bug

### PR DESCRIPTION
**Pull request by LuLaValva**
## Description

Months were being shifted on the first day of the month in CET timezone, an additional UTC cast fixed the issue.

### CODE REVIEW

**Comment by agliga** [comment]
Is this blocking? Do we need a patch or can it wait.

**Comment by LuLaValva** [comment]
> Do we need a patch or can it wait?

It depends how long we are waiting for, but I would like to get this in soon so I was thinking a patch was a good idea

**Comment by agliga** [comment]
> > Do we need a patch or can it wait?
> 
> 
> 
> It depends how long we are waiting for, but I would like to get this in soon so I was thinking a patch was a good idea

I understand. I think it's good to get it out soon
But our criteria for is only if the team is blocked completely and there is no workaround. 
So verify if this is blocking their release or code. If not we can put it in 12.8.0

**Comment by LuLaValva** [comment]
> > > Do we need a patch or can it wait?
> > 
> > 
> > 
> > It depends how long we are waiting for, but I would like to get this in soon so I was thinking a patch was a good idea
> 
> I understand. I think it's good to get it out soon
> But our criteria for is only if the team is blocked completely and there is no workaround. 
> So verify if this is blocking their release or code. If not we can put it in 12.8.0 

This is blocking, and there is no workaround. The team in question is looking to start demos next week, but this effects all teams that use date textbox.

**Pull request merged**
