### PR TITLE
fix(ts): Update to latest

### LINKED ISSUE #2303: typescript: update to latest
# Bug Report

## Description

- Marko TypeScript for `@attr` tags was improved and simplified, but it broke some workarounds in eBayUI
  - `Marko.RepeatableAttrTag` needs to be moved to `Marko.AttrTag` (they are now the same type)
  - We can not rely on repeated tags being arrays, and instead treat them as iterables.

### PR DESCRIPTION
**Pull request by LuLaValva**
- Fixes #2303 

## Description

- Modernize TS `@attr` Tags

## Context

- Attr tags have been simplified on the Marko side, but it means that a lot of the workarounds in eBayUI are now unnecessary or broken

### CODE REVIEW

**Comment by agliga** [comment]
CI is failing due to some TS errors

**Comment by LuLaValva** [comment]
Oh actually we're waiting on one more simple TS patch, I had it updated locally but didn't realize it wasn't included in `1.2.1`. Should be up soon.

**Comment by LuLaValva** [comment]
Okay, should be good now @agliga

**Review by agliga — APPROVED** [review]
Looks like there are some conflicts, but good to go

**Pull request merged**
