### PR TITLE
Select: fix value in change event

### PR DESCRIPTION
**Pull request by martin-ebay**
## Description
updated the call to update in the setSelectedOption map loop to prevent it from calling early

## Context
fix for issue #403

### CODE REVIEW

**Comment by seangates** [comment]
Should `this.update()` come after the `setState`?

**Comment by yomed** [comment]
Thanks for the PR. Please include a test case that was failing previously.

**Comment by martin-ebay** [comment]
@yomed 2 unit test added along with a second set of mock data

**Comment by msendlakowski** [comment]
@yomed  The unit test isn't fully testing the issue, but @martin-ebay is out of time.  Are you OK if we merge and publish this patch fix quickly.  And I'll follow up with a better test.

**Comment by yomed** [comment]
@martin-ebay Thanks for the attempt on the test. Since it appears very difficult to simulate this test, and because your tests do not fail before the fix, we decided to go ahead with the fix by itself.

**Pull request merged**
