### PR TITLE
Updated carousel with fade, peek, and, no dots 

### PR DESCRIPTION
**Pull request by agliga**
## Description
Added several carousel changes, added fade, removed dots, and added always peek on items-per-slide
This is the ebay-ui portion, see the skin for the fade 

## Context
* Added fade class only when `items-per-slide` is not set or if `autoplay` is not set or if the carousel is not scrolled to end.
* Forced `items-per-slide` peek value to be set at `0.1` if it is not set. 
* Removed all dots and accessitility text associated with it. Also removed all dots tests

## References
#1021
eBay/skin#988
PR with screenshots https://github.com/eBay/skin/pull/1002

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Not sure why the a11y status text is now appearing/visible?

Screen Shot 2020-01-30 at 11 25 15 AM

**Comment by agliga** [comment]
@imcburnie it seems to be a skin issue. Its not clipped anymore but the `clipped` class is there

**Comment by ianmcburnie** [comment]
Okay. I believe the `clipped` class comes from the skin utility module. The utility module is a dependency of the core module. The core module is required to be added by all pages.

**Comment by agliga** [comment]
> Okay. I believe the `clipped` class comes from the skin utility module. The utility module is a dependency of the core module. The core module is required to be added by all pages.

Fix for that is in #1043

**Pull request merged**
