### PR TITLE
Added aria-expanded to drawer handle and default aria-label

### PR DESCRIPTION
**Pull request by agliga**
## Description
Missing `aria-expanded` for drawer. Added it along with default aria-label text

### CODE REVIEW

**Review by ianmcburnie — CHANGES_REQUESTED** [review]
As discussed offline, let's go with `a11y-maximize-text` and `a11y-minimize-text` and no ARIA expanded or pressed, and I'll test it out.

**Comment by agliga** [comment]
> As discussed offline, let's go with `a11y-maximize-text` and `a11y-minimize-text` and no ARIA expanded or pressed, and I'll test it out.

Done,
basically when it's minimized will use `a11yMaximizeText` and when maximized will use `a11yMinimizeText`. This makes the most sense since you want to show the text of the action you will do.

**Review by ianmcburnie — APPROVED** [review]

**Review by ianmcburnie — CHANGES_REQUESTED** [review]
Oh wait, is this a breaking change....

**Comment by agliga** [comment]
> Oh wait, is this a breaking change....

I was thinking about it... 
We can set the default initially to what `a11yHandleLabel` is. If its not set, then we use the maximize or minimize
However I think that since the default is there we might not need it unless people are using the `a11yHandleText`

**Review by ianmcburnie — APPROVED** [review]

**Pull request merged**
