### PR TITLE
feat(flags): imported flags from skin as components

### PR DESCRIPTION
**Pull request by agliga**
## Description
Imported flags into ebayui. Added as a new module.

## References
https://github.com/eBay/ebayui-core/issues/2007

## Screenshots

Screenshot 2023-11-14 at 2 33 39 PM

### CODE REVIEW

**Comment by agliga** [comment]
CI will fail until we prepublish skin

**Review by LuLaValva — COMMENTED** [review]
Should we run prettier on all of these `.js` and `.json` files, to keep them consistent with the rest of the source? This is potentially also something we can add to the import script

**Comment by agliga** [comment]
> Should we run prettier on all of these `.js` and `.json` files, to keep them consistent with the rest of the source? This is potentially also something we can add to the import script

Every time we commit prettier is run on those files that were changed

**Review by saiponnada — APPROVED** [review]
LGTM

**Comment by LuLaValva** [comment]
> > Should we run prettier on all of these `.js` and `.json` files, to keep them consistent with the rest of the source? This is potentially also something we can add to the import script
> 
> Every time we commit prettier is run on those files that were changed

The files in this PR are not formatted with prettier.

**Comment by LuLaValva** [comment]
> > Should we run prettier on all of these `.js` and `.json` files, to keep them consistent with the rest of the source? This is potentially also something we can add to the import script
> 
> Every time we commit prettier is run on those files that were changed

Ah I see, it's just the other icons that aren't formatted. We should format them in a separate PR.

**Review by LuLaValva — APPROVED** [review]

**Pull request merged**
