### PR TITLE
Textbox: Additional types

### PR DESCRIPTION
**Pull request by seangates**
## Description
- add allowance for a "password" type

## Context
When working with users one of the immediate uses for textbox is as a password field. This allows support for that.

## References
Relates to #575

### CODE REVIEW

**Comment by ianmcburnie** [comment]
#575 has this marked for 2.1.0 release because technically it adds new functionality rather than fixing a bug. Could be persuaded otherwise if we feel this is urgent, but I was under the impression there was a workaround.

**Comment by seangates** [comment]
The workaround is after the page has loaded and pretty ... hacky. It requires a developer to modify the DOM, and not use Marko.

**Comment by seangates** [comment]
Also, this PR only includes the password type. I still believe #575 to be for 2.1.0, with thi PR addressing the immediate need.

**Comment by ianmcburnie** [comment]
Ok, it doesn't seem to be strictly following semver rules though. Just so we are all aware. 

Heads up that code coverage goes down slightly too for that uncovered code path, but maybe you are leaving that for when we add the other types too.

**Comment by seangates** [comment]
Yes, I saw the coverage drop and will address it in the full-featured PR.

**Comment by DylanPiercey** [comment]
Curious why we are not just allowing `type` to pass through?

**Comment by seangates** [comment]
Per a comment from @ianmcburnie in our standup I went with "just allow password".

**Comment by ianmcburnie** [comment]
We could do that, but then it opens it up to type=checkbox, type=radio, etc. which make no sense.

**Comment by senthilp** [comment]
@ianmcburnie How will types like `email`, `tel` etc. work? Should we check on a whitelist then?

**Comment by ianmcburnie** [comment]
We'll just go through them one by one, in different browsers and devices and see which ones work "as is". I imagine most of the obvious ones will be fine.

**Pull request merged**
