### PR TITLE
Added details component

### PR DESCRIPTION
**Pull request by agliga**
## Description
Added new details component based on skin markup

## Context
* Added two events for details open/close
* Added a size and type options. I could have done just  center=true and small=true, but who knows if we want to expand those at a later time and they go in line with other components
* Added open as a state variable, although the browser handles the open/close. 

## References
#660 

## Screenshots
Screen Shot 2020-02-27 at 11 01 16 AM

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Here's a quick one, all the examples show "Detals" instead of "Details" :-)

**Comment by DylanPiercey** [comment]
Shouldn't we have some browser tests as well to check the toggle functionality/events?

**Comment by agliga** [comment]
> Shouldn't we have some browser tests as well to check the toggle functionality/events?

I was thinking about that, however that should be handled by marko correct? All it's doing is just emitting an event on open/close which should be handled by marko, so no reason to test that correct?
For open/close, it's actually mostly using native browser implementation. The open/close state is mostly for the initial load (and toggling it is just so it doesn't always stay open when clicked)

**Comment by DylanPiercey** [comment]
@agliga part of the public API for the component is the events it emits and so we still need to test that those are coming through when / how we expect.

Also I think we should not use `onClick` and instead `onToggle` for the details element (https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/toggle_event)

**Comment by DylanPiercey** [comment]
`<details>` also has an `open` property with the `open` state. We could avoid using state here all together and just use that for emitting the right event.

**Comment by agliga** [comment]
Added one more change to add client tests and to sync open property on client

@DylanPiercey Can you take another look 👍

**Comment by agliga** [comment]
@DylanPiercey Removed all getByTestId and used closest instead.

**Pull request merged**
