### PR TITLE
Integrate icon into carousel and dialog

### PR DESCRIPTION
**Pull request by yomed**
## Description

- add `<ebay-icon>` to carousel and dialog templates
- add `/ebay-icon` to the browser.json files (with minor reordering cleanup)

## Context

I'm leaving the menu/select for later since I think those would work better with Skin changes (https://github.com/eBay/ebayui-core/issues/172).

@PrashantAshok You should be able to update checkbox/radio to use this pattern. If we want to get those in quickly, I can also just apply this to those components as part of this PR (after they're merged).

@DylanPiercey I'm leaving the dynamic demo setup alone for now, because most icons are being imported by the `<ebay-icon>` examples, which are getting cached since every component uses the same template.

## References

Follow up to https://github.com/eBay/ebayui-core/pull/136

### CODE REVIEW

**Comment by PrashantAshok** [comment]
I might be wrong, but didn't we discuss not to add `ebay-icon` to other components, because of issues involved with SPA. @senthilp?

**Comment by senthilp** [comment]
Yes, that seems right. We will sync-up on this as a group and make a call.

**Comment by yomed** [comment]
There shouldn't be an issue using `<ebay-icon>` in SPAs (either on it's own, or in components). It's just that SPA teams will need to handle their own stamping, rather than relying on our magic stamper.

**Comment by senthilp** [comment]
Will you be using inline or background for carousel and dialog?

**Comment by yomed** [comment]
Sorry, the diff is clearer now after rebase. @senthilp Carousel and dialog use inline because both cases need to change the icon color during interaction.

**Pull request merged**
