### PR TITLE
Add fixed height and truncated options to btn;

### PR DESCRIPTION
**Pull request by seangates**
## Description
- added `fixed` boolean attribute (UPDATE: now changed to `fixed-height`)
- added `truncate` boolean attribute

## Context
Recent changes in Skin to how overflow and wrapping work with the button have then created two new modifiers: one for fixed heigh (sized heights) and truncation.

## References
Completes #462 

This will go into 2.0.0 branch (when we create it).

### CODE REVIEW

**Comment by ianmcburnie** [comment]
To be less ambiguous, I'd prefer `fixed-height` over `fixed`.

**Comment by seangates** [comment]
@senthilp @ianmcburnie Updated. Please review again.

**Comment by seangates** [comment]
@ianmcburnie It hasn't done the truncation yet. Future tense v. past tense. 🤷‍♂️

**Comment by seangates** [comment]
I can change it though, if you think it would help.

**Comment by ianmcburnie** [comment]
Good point! Let's keep it as is.

**Pull request merged**
