### PR TITLE
Switch Component

### LINKED ISSUE #280: New Component: Switch
This will be available for DS4 and DS6 in upcoming Skin v6 release. Should be a simple component to squeeze into v1.0.0.

Sneak peak:

screen shot 2018-07-20 at 2 48 27 pm

New markup:

```html
<span class="switch">
    <input role="switch" type="checkbox" />
    <span class="switch__inner"></span>
</span>
```

### PR DESCRIPTION
**Pull request by yomed**
## Description

- adds new switch component

## Context

Overall, code is very similar to the `checkbox` component.
Currently only supports DS4.

## References

Closes #280 

## Screenshots

screen shot 2018-08-03 at 4 23 35 pm

### CODE REVIEW

**Comment by senthilp** [comment]
LGTM

**Comment by yomed** [comment]
@DylanPiercey I agree that the event name seems off (was just trying to stay consistent with the others). 
@PrashantAshok Do you recall why those names were chosen? https://github.com/eBay/ebayui-core/pull/133#issuecomment-390764890

**Comment by yomed** [comment]
Created follow-up issue #320 for the event naming.

**Comment by PrashantAshok** [comment]
More details [here](https://github.com/eBay/ebayui-core/pull/134#issuecomment-390281822)

**Comment by DylanPiercey** [comment]
@PrashantAshok regarding the linked conversation: How does `radio-change` conflict with the native `change`? That should have been fine?

**Comment by sendlo** [comment]
It looks like @ianmcburnie specifically wanted to differentiate it from the dom event.  And then they landed on all the events across the components to be "x-select".

I think we have two options for all the "select" events on our components.  We either mimic the dom event names, meaning all events will get different names based on its HTML counterpart.  Or we keep a consistent naming convention like "x-select" across our components.

Unless anyone has a really strong feeling about this, I think keeping them as "x-select" is fine.

**Comment by yomed** [comment]
I think `x-select` is fine for components where the behavior is only selection (breadcrumb, tab, pagination). But for components where the event is used for both selection and deselection (radio, checkbox, switch), we should use something else, like `x-change`.

**Comment by PrashantAshok** [comment]
@yomed , @hramakumar - sorry for commenting on a closed PR, but switch (which radio/checkbox has) also has the spacing/`undefined` issue. [fyi](https://github.com/eBay/ebayui-core/issues/200). This would a fix in Skin for switch.

**Pull request merged**
