### PR TITLE
Button: Fixes CTA variant

### LINKED ISSUE #568: Button: CTA variant not accounted for
CTA variant of button is mentioned in the docs, but is a no-op when applied.

For first version, we *may* just want to tackle the default CTA colour, rather than all the colour variants.

Blocked by: https://github.com/eBay/skin/issues/574

### PR DESCRIPTION
**Pull request by seangates**
## Description
- fixes CTA button variant
- adds `ebay-icon`
- new support for a CTA button in DS4

## Context
CTA button variant was not working correctly.

## References
Fixes #568 

### Before
image
image

### After
image
image

### CODE REVIEW

**Comment by seangates** [comment]
I will add another example with the additional color classes for DS6.

**Comment by ianmcburnie** [comment]
I thought we said we weren't going to do the other colours? As we only have them in ds6 right now.

**Comment by seangates** [comment]
Okay. That's fine if we want to leave them out. I just added it with a "ds6 only" description. 🤷‍♂️

**Comment by ianmcburnie** [comment]
I'll keep this as 2.1.0 release. We can push editable combobox back to 2.2.0

**Pull request merged**
