### PR TITLE
feat(carousel): added support for default-tabindex

### PR DESCRIPTION
**Pull request by agliga**
## Description
Added `default-tabindex` option to any focusable element to basically allow a default to be set when carousel changes the tabindex on an item
Added an example of that to the page. (I'm happy to change it as needed but it should be pretty basic)
Also updated readme for carousel to use new pattern.

## References
https://github.com/eBay/ebayui-core/issues/1762

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Is `default-tabindex` going on a native HTML element? If so, shouldn't we use a data attribute? Something like `data-carousel-default-tabindex`?

**Comment by agliga** [comment]
> Is `default-tabindex` going on a native HTML element? If so, shouldn't we use a data attribute? Something like `data-carousel-default-tabindex`?

Yes, you're right.

**Review by LuLaValva — APPROVED** [review]
I'm not sure if this is the cleanest way to allow tab index and it's a little strange to be using the `dataset` directly, but it looks like it is working on my end so I will approve.

**Comment by agliga** [comment]
> I'm not sure if this is the cleanest way to allow tab index and it's a little strange to be using the `dataset` directly, but it looks like it is working on my end so I will approve.

So here's why:

Basically we are scanning each element inside the carousel and seeing if it's a focusable element (button/link etc). And for all those focusable elements, we either remove or set a tabindex to -1 if it's either in view or obscured by the carousel. 

The problem is we don't know what the initial tabindex was. We can try to save the first render tabindex, but if it changes in anyway, it could cause issues or not render correctly. 

This change is supposed to solve that by allowing users to specify the tabindex they want it restored to by using a data-attribute. This way we won't be guessing what the right tabindex is.

**Comment by agliga** [comment]
I'm going to merge, if there are any issues I can fix them in a followup PR

**Pull request merged**
