### PR TITLE
#285 allow external icons

### PR DESCRIPTION
**Pull request by partynuts**
PLEASE SQUASH.

## Description
allow use of external icons in ebay-icon component

## References
https://github.com/eBay/ebayui-core/pull/281
https://github.com/eBay/ebayui-core/issues/285
http://localhost:6006/?path=/story/ebay-icon--inline-custom-symbol

### CODE REVIEW

**Comment by ianmcburnie** [comment]
I also need to change the target from 4.3.0 to 4.4.0 for this one. Please rebase your local branch with 4.4.0 then force push your feature branch.

**Comment by seangates** [comment]
Finally got the branches all figured out. The change set is much better now, @ianmcburnie.

**Comment by seangates** [comment]
@agliga We'll talk about this offline in standup, if that's okay. We do want to make sure this addresses the question at hand: allowing custom icons. Where those icons live, and how we reference them, is up for debate.

**Comment by ianmcburnie** [comment]
@seangates Is this one ready for review? I think it could also benefit from a meeting to walk through it.

**Comment by seangates** [comment]
@ianmcburnie I don't believe it's ready, actually. Yes, it would be good to go over it.

**Comment by ianmcburnie** [comment]
@seangates Want to keep this one open? Would be great if you can see it out to completion and prevent the branch from getting stale. We can punt it to v5.

**Comment by seangates** [comment]
Well, it was an old backlog item, and it's not a big priority. Let's close the PR, as all the changes are intact.

**Comment by ianmcburnie** [comment]
Ok. Will do. Would be great if you could pick it up again at some point. I don't think anybody else will in the near future.

**Pull request closed without merging**
