### PR TITLE
Component: ebay-dialog

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
Adds the `<ebay-dialog>` component mentioned in #6.
<strike>Be sure to `yarn link @ebay/skin` using my branch [here](https://github.com/eBay/skin/tree/6-ebay-dialog).</strike> (now using skin 4 prerelease)

## Notes

1. There is some weirdness involved in getting the `makeup-js` libraries to work properly with Marko. As you can see in this PR I have setup the widgets lifecycle events to remove any DOM mutations created by makeup before rendering, and then reapplying the mutations after Marko applies it's update.

2. Transitions are automatically enabled based off the type of modal dialog (eg: panel-left slides in from the left).

## References
#6

## Screenshots

*Basic Dialog Example*
screen shot 2018-04-04 at 9 59 12 am

### CODE REVIEW

**Comment by DylanPiercey** [comment]
Just rebased based on the `0.2.0` changes. Also updated to work with my changes to @ebay/skin. Ready for some review 😄.

**Comment by ianmcburnie** [comment]
Like the carousel PR, this will also go into 0.3.0 branch when it's ready. 0.3.0 is going to be mega!

**Comment by DylanPiercey** [comment]
Whoops, will rebase accordingly.

**Comment by ianmcburnie** [comment]
@DylanPiercey There are some minor conflicts. Might need another rebase with 0.2.0.

**Comment by DylanPiercey** [comment]
@ianmcburnie rebased with `0.2.0` again and added my changes mentioned earlier today. Do note the current PR does not work if you use `ebay-carousel` at the same time because of `ds4` icons used there. Let me know if I've missed anything.

**Comment by ianmcburnie** [comment]
@DylanPiercey Travis error:

screen shot 2018-04-09 at 1 56 19 pm

**Comment by DylanPiercey** [comment]
Woops. I'll fix that asap.

**Comment by DylanPiercey** [comment]
Should be fixed now... Not sure why coveralls is freaking out.

**Comment by ianmcburnie** [comment]
@DylanPiercey I'm seeing an issue with the panel right animation on the examples page. In Safari & Chrome.

**Comment by DylanPiercey** [comment]
I have updated the PR with the following:

1. Switched back to inline svg instead of background svg.
2. Switched focus to be set after transitioning (except on first render).
3. `dialog-show` and `dialog-close` events are now called after any css transition.

**Pull request merged**
