### PR TITLE
Fixes unrecognized tag issue in Marko v4 and dash transform issue.

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
The `marko.json` inside of each component (which contained the transform information) was only scoped relative to that folder which meant that the examples were loaded correctly but if you tried to actually use the component from outside the examples it was not working. This was fixed by moving all relevant `marko.json` config to the top level.

Also when using with Marko v4 the transform was being applied too late which caused an `unrecognized tag` error to be thrown. The fix for this was to include the child option tag names in the `marko.json` as well (the config for them is empty though) so that when Marko v4 is parsing it knows that they are in fact custom tags.

## Related Issue
issue https://github.com/eBay/ebayui-core/issues/11
issue https://github.com/eBay/ebayui-core/issues/13

### CODE REVIEW

**Comment by seangates** [comment]
So ... the components themselves won't carry the tag definition?

**Comment by DylanPiercey** [comment]
@seangates I'm trying out another solution which may allow for the tag definitions to be relative to the component. Will update the PR if this works...

**Comment by seangates** [comment]
@DylanPiercey So, it's still required to have this at the root, all in one large file?

**Comment by DylanPiercey** [comment]
@seangates currently pushing a fix and rebase (this was a couple typo's which @yomed and I caught earlier today). I tried to set this up with relative tag definitions however I was running into some errors that I haven't been able to resolve yet.

I think for now it would be best to just have all of this defined top level.

**Pull request merged**
