### PR TITLE
feat: added async loading support

### PR DESCRIPTION
**Pull request by agliga**
## Description
* In order to make it so we dont upload compiled files to the CDN I changed the loading portion of our modules to load modules asynchronously. 
* Changed model-viewer, highcharts, and shaka-player to load asynchronously. 
* The changes to package.json, and prettier are needed because we introduced a nested `node_modules` directory

## Context
* Part of the issue is we need to support lasso and webpack async. These load modules asynchronously very differently.
* We added a "fake" `node_module` directory where we load a module using `import()` if its vite or webpack, but if its lasso we load it using `lassoLoader`
* The reason why there are multiple modules is mainly for bundling purposes. These will all be indexed properly. 
* These also need to be tested in a prerelase to verify that this is working fine is all various types of apps. 

__note__ I had to disable a highcharts test because it was not finding the text correctly. 

## References
https://github.com/eBay/ebayui-core/issues/2305

### CODE REVIEW

**Comment by mikehobi** [comment]
@agliga quick glance at it, looks like pattern-fill is not working properly

image

**Comment by agliga** [comment]
> @agliga quick glance at it, looks like pattern-fill is not working properly
> 
> image

What would cause this problem?

**Comment by mikehobi** [comment]
> > @agliga quick glance at it, looks like pattern-fill is not working properly
> > image
> 
> What would cause this problem?

I think accessibility and pattern fill need to be initialized?

Something like this might work:

```
        highChartsLoad()
            .then(([highcharts, accessibility, patternFill]: any) => {
                window.Highcharts = highcharts.default;

                accessibility.default(window.Highcharts);

                patternFill.default(window.Highcharts);

                this.handleSuccess();
            })
            .catch((e: Error) => {
                this.handleError(e);
            });
```

**Comment by agliga** [comment]
Should be good to go. Fixed mikes issue
Also the license thing is probably due to highcharts being a depdency now. I will ignore this since this is documented properly.

**Pull request closed without merging**
